[project]
name = "homeric_greek_inflection_tester"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Paul Han", email = "paulh@dtric.com"},
]
dependencies = []
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
